apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/eureka-server:8
          ports:
            - name: http-port
              containerPort: 8060
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server:8060/eureka
            - name: EUREKA_PORT
              value: "8060"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: sba
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
  type: NodePort
