apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/eureka-server:latest
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: sba
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
