spring:
  profiles: dev
  datasource:
    url: ${ACCOUNT_DS_URL}
    username: ${ACCOUNT_DS_USERID}
    password: ${ACCOUNT_DS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/import.sql
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
---
spring:
  profiles: prod
  datasource:
    url: ${ACCOUNT_DS_URL}
    username: ${ACCOUNT_DS_USERID}
    password: ${ACCOUNT_DS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/import.sql
    initialization-mode: never
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
