spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: ${SCHOOL_DS_URL:jdbc:mysql://localhost:3306/account?useSSL=false}
    username: ${SCHOOL_DS_USERID:root}
    password: ${SCHOOL_DS_PASSWORD:rootpassword}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: batch
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
server:
  port: 9999

---
spring:
  profiles: prod
  datasource:
    url: ${SCHOOL_DS_URL:jdbc:mysql://localhost:3306/account?useSSL=false}
    username: ${SCHOOL_DS_USERID:root}
    password: ${SCHOOL_DS_PASSWORD:rootpassword}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: batch
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
server:
  port: 80
