spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        mod: debug
---
spring:
  profiles: prod
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
