apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-zuul
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-zuul
  template:
    metadata:
      labels:
        app: gateway-zuul
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/gateway-zuul:latest
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server/eureka

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-zuul
  namespace: sba
spec:
  selector:
    app: gateway-zuul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
