version: '3.7'

services:
  account-service:
    image: registry.cn-hangzhou.aliyuncs.com/huimiao/gateway-zuul:1
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL: http://host.docker.internal:8060/eureka
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access:

