spring:
  datasource:
    url: ${SCHOOL_DS_URL}
    username: ${SCHOOL_DS_USERID}
    password: ${SCHOOL_DS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug

---
spring:
  datasource:
    url: ${SCHOOL_DS_URL}
    username: ${SCHOOL_DS_USERID}
    password: ${SCHOOL_DS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  profiles: prod
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug
