apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/auth-svc:{version}
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server/eureka

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: sba
spec:
  selector:
    app: auth-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
