apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-svc
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-svc
  template:
    metadata:
      labels:
        app: training-svc
    spec:
      containers:
        - name: training-svc
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/training-svc:{version}
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server/eureka
            - name: SCHOOL_DS_URL
              value: jdbc:mysql://mysql-svc:3306/school?useSSL=false
            - name: SCHOOL_DS_USERID
              value: root
            - name: SCHOOL_DS_PASSWORD
              value: rootpassword

---
apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: sba
spec:
  selector:
    app: training-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
