pipeline {
  agent any
  environment {
    GIT_URL = "git@github.com:huimiao/SBA_MentorOnDemand.git"
    GIT_CRED = "0175370e-5e36-457f-8d4a-a4adff3327f3"
    DOCKER_REPO="registry.cn-hangzhou.aliyuncs.com/huimiao/training-svc"
    DOCKER_REG="https://registry.cn-hangzhou.aliyuncs.com"
    DOCKER_REG_KEY = "331a6a07-264c-4863-b96d-65384d942cd7"
    dockerImage = ''
  }
  stages {
    stage('CheckOut Code'){
      steps{
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: GIT_CRED, url: GIT_URL]]])
      }
    }
    stage('Maven Build'){
      steps{
        sh 'mvn clean install -DskipTests'
      }
    }
    stage('Building image') {
      steps{
        script {
            docker.withRegistry( DOCKER_REG, DOCKER_REG_KEY ) {
	               dockerImage = docker.build(DOCKER_REPO + ":$BUILD_NUMBER", "./training-svc/")

            }
        }
      }
    }
     stage('Push Image') {
       steps{
         script {
           docker.withRegistry( DOCKER_REG, DOCKER_REG_KEY ) {
              dockerImage.push()
           }
         }
       }
    }
    stage('Deploy Image to K8s') {
      steps{
        script {
          sh "sed -i 's/{version}/" + BUILD_NUMBER + "/g' ./training-svc/deployment.yml"
    	  sh 'kubectl apply -f ./training-svc/deployment.yml'
    	}
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $DOCKER_REPO:$BUILD_NUMBER"
      }
  }
  }
}
