apiVersion: apps/v1
kind: Deployment
metadata:
  name: technology-svc
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technology-svc
  template:
    metadata:
      labels:
        app: technology-svc
    spec:
      containers:
        - name: technology-svc
          image: registry.cn-hangzhou.aliyuncs.com/huimiao/technology-svc:10
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: spring_profiles_active
              value: prod
            - name: EUREKA_URL
              value: http://eureka-server/eureka
            - name: TECHNOLOGY_DS_URL
              value: jdbc:mysql://mysql-svc:3306/technology?useSSL=false
            - name: TECHNOLOGY_DS_USERID
              value: root
            - name: TECHNOLOGY_DS_PASSWORD
              value: rootpassword

---
apiVersion: v1
kind: Service
metadata:
  name: technology
  namespace: sba
spec:
  selector:
    app: technology-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
