insert skills(name) values('AngularJS');
insert skills(name) values('Java');
insert skills(name) values('RabiitMQ');
insert skills(name) values('Jenkins');
insert skills(name) values('Docker');
insert skills(name) values('Kubernetes');
insert skills(name) values('Spring Core');
insert skills(name) values('Spring Boot');
insert skills(name) values('Spring Cloud');
insert skills(name) values('HTML5');
insert skills(name) values('CSS3');
insert skills(name) values('Javascript');
insert skills(name) values('React');
insert skills(name) values('Redux');
insert skills(name) values('JMeter');
insert skills(name) values('Java 8');
insert skills(name) values('JQuery');
insert skills(name) values('JWT');
insert skills(name) values('OAuth2');
insert skills(name) values('Tomcat');
insert skills(name) values('Jetbrains IDEA');
